# Generated by Django 5.1.1 on 2024-09-13 22:02

import apps.cinema.models
import config.settings
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('duration', models.PositiveIntegerField(default=180, help_text='Duration in minutes')),
                ('image', models.ImageField(storage=config.settings.Liara(default_acl='public-read'), upload_to=apps.cinema.models.Movie.upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='OnScreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slots', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('10:00-13:00', 'morning'), ('14:00-17:00', 'afternoon'), ('20:00-23:00', 'evening')], max_length=300), size=None)),
                ('seats', models.JSONField(default=apps.cinema.models.OnScreen.get_default_schedule)),
                ('date', models.DateField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled', to='cinema.movie')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('movie', 'date'), name='unique_movie')],
            },
        ),
    ]
